config/routes.rb
Rails.application.routes.draw do
  resources :topics do
     resources :posts, except: [:index]
     resources :sponsored_posts, except: [:index]
   end
  
  resources :users, only: [:new, :create]
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :questions

  resources :advertisements

  get 'about' => 'welcome#about'
  
  post 'users/confirm' => 'users#confirm'

  root 'welcome#index'
  

  
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new
    @question.title = params[:question][:title]
    @question.body = params[:question][:body]
  
    if @question.save
      flash[:notice] = "Question was saved. Yee hoo."
      redirect_to @question
    else
      flash.now[:alert] = "There was an error saving your question. Why? Good question."
      render :new
    end
  end
  
  def edit
    @question = Question.find(params[:id])
  end
  
  def update
    @question = Question.find(params[:id])
    @question.title = params[:question][:title]
    @question.body = params[:question][:body]
    @question.resolved = params[:question][:resolved]
    
    if @question.save
      flash[:notice] = "\"#{@question.title}\" was saved successfully."
      render :show
    else
      flash.now[:alert] = "There was an error saving your question."
      render :edit
    end
  end
  
  def destroy
    @question = Question.find(params[:id])
    
    if @question.destroy
      flash[:notice] = "Your question was successfully deleted."
      redirect_to questions_path
    else
      flash.now[:alert] = "There was an error deleting your question."
      render :show
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<div class="row">
    <div class="col-md-4">
        <p>Guidelines</p>
        <ul>
            <li>Don't get too curious.</li>
            <li>If we say "Not Now Murray. Not NOW Murray. NOT. NOW. MURRAY!" don't take offense. It simply means the Belluminati has hacked into Bloccit and you can never be too safe. </li>
        </ul>
    </div>
    <div class="col-md-8">
        <%= form_for @question do |f| %>
        <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: "form-control", placeholder: "Enter a title" %>
        </div>
        <div class="form-group">
            <%= f.label :body %>
            <%= f.text_area :body, rows: 8, class: "form-control", placeholder: "Enter your question" %>
        </div>
        <div class="form-group">
            <%= f.label :resolved, "Resolved?" %>
            <%= f.check_box :resolved %>
        </div>
        <div class="form-group">
            <%= f.submit "Save", class: "btn btn-success" %>
        </div>
        <% end %>
    </div>
</div>

app/views/questions/index.html.erb
<h1>Every Question known to man <%= link_to "New", new_question_path(@question), class: "btn btn-success" %></h1>
<% @questions.each_with_index do | question, index | %>
    <div class="media">
        <div class="media-body">
            <h4 class="media-heading">
                <%= link_to question.title, question %>
                <% if question.resolved == true %>
                    <i>(Resolved)</i>
                <% end %>
            </h4>
        </div>
    </div>
<% end %>

app/views/questions/new.html.erb
<h1>Ask a Question already</h1>
<div class="row">
    <div class="col-md-4">
        <p>Guidelines</p>
        <ul>
            <li>Don't get too curious.</li>
            <li>If we say "Not Now Murray. Not NOW Murray. NOT. NOW. MURRAY!" don't take offense. It simply means the Belluminati has hacked into Bloccit and you can never be too safe. </li>
        </ul>
    </div>
    <div class="col-md-8">
        <%= form_for @question do |f| %>
            <div class="form-group">
                <%= f.label :title %>
                <%= f.text_field :title, class: "form-control", placeholder: "Enter a title for this question" %>
            </div>
            <div class="form-group">
                <%= f.label :body %>
                <%= f.text_area :body, rows:8, class: "form-control", placeholder: "Enter a gist of your question" %>
            </div>
            <div class="form-group">
                <%= f.submit "Save", class: "btn btn-success" %>
            </div>
        <% end %>
    </div>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<div class="row">
    <div class="col-md-8">
        <%= @question.body %>
    </div>
    <div class="col-md-4">
        <%= link_to "Edit", edit_question_path(@question), class: "btn btn-success" %>
        <%= link_to "Delete Question", @question, method: :delete, class: "btn btn-danger", data: { confirm: "I gotta question for you: Are. You. Sure?" } %>
    </div>
</div>