config/routes.rb
Rails.application.routes.draw do
  resources :topics do
     resources :posts, except: [:index]
     resources :sponsored_posts, except: [:index]
   end
  
  resources :users, only: [:new, :create]
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :questions

  resources :advertisements

  get 'about' => 'welcome#about'
  
  post 'users/confirm' => 'users#confirm'

  root 'welcome#index'
  

  
end

app/models/topic.rb
class Topic < ActiveRecord::Base
    has_many :posts, dependent: :destroy
    has_many :sponsored_posts, dependent: :destroy
    
    validates :name, length: { minimum: 5 }, presence: true
    validates :description, length: { minimum: 15 }, presence: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
    def index
        @topics = Topic.all
    end
    
    def show
        @topic = Topic.find(params[:id])
    end
    
    def new
        @topic = Topic.new
    end
    
    def create
        @topic = Topic.new(topic_params)
        # @topic.name = params[:topic][:name]
        # @topic.description = params[:topic][:description]
        # @topic.public = params[:topic][:public]
        
        if @topic.save
            redirect_to @topic, notice: "Topic was save successfully!"
        else
            flash.now[:alert] = "There was an error saving your topic. Please try again."
            render :new
        end
    end
    
    def edit
        @topic = Topic.find(params[:id])
    end
    
    def update
        @topic = Topic.find(params[:id])
        @topic.assign_attributes(topic_params)
        # @topic.name = params[:topic][:name]
        # @topic.description = params[:topic][:description]
        # @topic.public = params[:topic][:public]
        
        if @topic.save
            flash[:notice] = "Topic was saved"
            redirect_to @topic
        else
            flash.now[:alert] = "There was an error updating your topic. Please try again."
            render :edit
        end
    end
    
    def destroy
       @topic = Topic.find(params[:id])
       
       if @topic.destroy
           flash[:notice] = "\"#{@topic.name}\" was deleted successfully!"
           redirect_to action: :index
       else
           flash.now[:alert] = "There was an error deleting your topic. Please try again."
           render :show
       end
    end
    
    private
    def topic_params
        params.require(:topic).permit(:name, :description, :public)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for [topic] do |f| %>
    <% if topic.errors.any? %>
        <div class="alert alert-danger">
            <h4>You have <%= pluralize(topic.errors.count, "error") %>.</h4>
            <ul>
                <% topic.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    
    <%= form_group_tag(topic.errors[:name]) do %>
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control", placeholder: "Enter a name" %>
    <% end %>
    
    <%= form_group_tag(topic.errors[:description]) do %>
        <%= f.label :description %>
        <%= f.text_area :description, rows: 8, class: "form-control", placeholder: "Enter topic description" %>
    <% end %>

    <div class="form-group">
        <%= f.submit "Save", class: "btn btn-success" %>
    </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>
<div class="row">
    <div class="col-md-4">
        <p>Guidelines for posts</p>
            <ul>
                <li>Make sure it rhymes.</li>
                <li>Don't use the letter "A".</li>
                <li>The incessant use of hastags will get you banned.</li>
            </ul>
    </div>
    <div class="col-md-8">
        <%= render partial: 'form', locals: { topic: @topic } %>
    </div>
</div>

app/views/topics/index.html.erb
<h1>Topics</h1>

<div class="row">
    <div class="col-md-8">
        <% @topics.each do |topic| %>
            <div class="media">
                <div class="media-body">
                    <h4 class="media-heading">
                        <%= link_to topic.name, topic %>
                    </h4>
                    <small>
                        <%= topic.description %>
                    </small>
                </div>
            </div>
        <% end %>
    </div>
    <div class="col-md-4">
        <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
    </div>
</div>

app/views/topics/new.html.erb
<div class="row">
    <div class="col-md-4">
        <p>Guidelines for topics</p>
        <ul>
            <li>Make sure it rhymes.</li>
            <li>Don't use the letter "8".</li>
            <li>The incessant use of hastags will get you banned.</li>
        </ul>
    </div>
    <div class="col-md-8">
        <%= render partial: 'form', locals: { topic: @topic } %>
    </div>
</div>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>

<%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
<%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %>
<div class="row">
    <div class="col-md-8">
        <p class="lead"><%= @topic.description %></p>
        <% @topic.posts.each do |post| %>
        
            <div class="media">
                <div class="media-body">
                    <h4 class="media-heading">
                        <%= link_to post.title, topic_post_path(@topic, post) %>
                    </h4>
                    <small>
                        submitted <%= time_ago_in_words(post.created_at) %> ago <br>
                        <%= post.comments.count %> Comments
                    </small>
                </div>
            </div>
        <% end %>
    </div>
    <div class="col-md-4">
        <%= link_to "New Post", new_topic_post_path(@topic), class: "btn btn-success" %>
        <%= link_to "New Sponsored Post", new_topic_sponsored_post_path(@topic), class: "btn btn-info" %>
    </div>
</div>
        