config/routes.rb
Rails.application.routes.draw do
  resources :topics do
     resources :posts, except: [:index]
     resources :sponsored_posts, except: [:index]
   end
  
  resources :users, only: [:new, :create]
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :questions

  resources :advertisements

  get 'about' => 'welcome#about'
  
  post 'users/confirm' => 'users#confirm'

  root 'welcome#index'
  

  
end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  def index
    @advertisements = Advertisement.all
  end

  def show
    @advertisement = Advertisement.find(params[:id])
  end

  def new
    @advertisement = Advertisement.new
  end

  def create
    @advertisement = Advertisement.new
    p params
    @advertisement.title = params[:advertisement][:title]
    @advertisement.copy = params[:advertisement][:copy]
    @advertisement.price = params[:advertisement][:price]
    
    if @advertisement.save
      flash[:notice] = "Advertisement was saved."
      redirect_to @advertisement
    else
      
      flash.now[:alert] = "There was an error saving the ad. Please try again."
      render :new
    end
  end
  
  def edit
    @advertisement = Advertisement.find(params[:id])
  end
  
  def update
    @advertisement = Advertisement.find(params[:id])
    @advertisement.title = params[:advertisement][:title]
    @advertisement.copy = params[:advertisement][:copy]
    @advertisement.price= params[:advertisement][:price]
    
    if @advertisement.save
      flash[:notice] = "Ad was updated."
      render :show
    else
      flash.now[:alert] = "There was an error updating this ad."
      render :edit
    end
  end
  
  def destroy
    @advertisement = Advertisement.find(params[:id])
    
    if @advertisement.destroy
      flash[:notice] = "\"#{@advertisement.title}\" was deleted successfully."
      redirect_to advertisements_path
    else
      flash.now[:alert] = "There was an error deleting this ad."
      render :show
    end
  end
end

app/helpers/advertisement_helper.rb
module AdvertisementHelper
end

app/views/advertisements/edit.html.erb
<h1>Edit Ad</h1>

<div class="row">
    <div class="col-md-4">
        <p>Guidelines for Ads</p>
        <ul>
            <li>Just kidding.</li>
            <li>Go crazy.</li>
        </ul>
    </div>
    <div class="col-md-8">
        <%= form_for @advertisement do |f| %>
        <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title,class: "form-control", placeholder: "Enter a title" %>
        </div>
        <div class="form-group">
            <%= f.label :copy %>
            <%= f.text_area :copy, rows: 8, class: "form-control", placeholder: "Enter some body copy" %>
        </div>
        <div class="form-group">
            <%= f.label :price %>
            <%= f.number_field :price, class: "form-control", placeholder: "Enter a price" %>
        </div>
        <div class="form-group">
            <%= f.submit "Save", class: "btn btn-success" %>
        </div>
        <% end %>
    </div>
</div>

app/views/advertisements/index.html.erb
<h1>All Ads <%= link_to "New", new_advertisement_path(@advertisement), class: "btn btn-success" %></h1>
<% @advertisements.each_with_index do |advertisement, index| %>
    <div class="media">
        <div class="media-body">
            <h4 class="media-heading">
                <%= link_to advertisement.title, advertisement %>
            </h4>
        </div>
    </div>
<% end %>

app/views/advertisements/new.html.erb
<h1>Make an Ad</h1>

<div class="row">
    <div class="col-md-4">
        <p>Guidelines for Ads</p>
        <ul>
            <li>Just kidding.</li>
            <li>Go crazy.</li>
        </ul>
    </div>
    <div class="col-md-8">
        <%= form_for @advertisement do |f| %>
            <div class="form-group">
                <%= f.label :title %>
                <%= f.text_field :title, class: 'form-control', placeholder: "Enter advertisement title" %>
            </div>
            <div class="form-group">
                <%= f.label :copy %>
                <%= f.text_area :copy, rows: 8, class: 'form-control', placeholder: "Enter advertisement copy" %>
            </div>
            <div class="form-group">
                <%= f.label :price %>
                <%= f.number_field :price, class: 'form-control', placeholder: "Enter advertisement price" %>
            </div>
            <div class="form-group">
                <%= f.submit "Save", class: 'btn btn-success' %>
            </div>
        <% end %>
    </div>
</div>

app/views/advertisements/show.html.erb
<h1><%= @advertisement.title %></h1>
<div class="row">
    <div class="col-md-8">
        <p><%= @advertisement.copy %></p>
        <p>Price: $<%= @advertisement.price %></p>
    </div>
    <div class="col-md-4">
        <%= link_to "Edit", edit_advertisement_path(@advertisement), class: "btn btn-success" %>
        <%= link_to "Delete Ad", @advertisement, method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure you want this Ad to be gone?" } %>
    </div>
</div>