config/routes.rb
Rails.application.routes.draw do
  resources :topics do
     resources :posts, except: [:index]
     resources :sponsored_posts, except: [:index]
   end
  
  resources :users, only: [:new, :create]
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :questions

  resources :advertisements

  get 'about' => 'welcome#about'
  
  post 'users/confirm' => 'users#confirm'

  root 'welcome#index'
  

  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>
<button class="social-btn"><%= link_to "Connect with Me on Facebook", "http://zombo.com" %></button>

app/views/welcome/index.html.erb
<div class="jumbotron">
    <h1>Bloccit</h1>
    <p>Bloccit is a resource for sharing links with your friends!</p>
    <p>
        <%= link_to "Sign In", new_session_path %> or
        <%= link_to "Sign Up", new_user_path, class: 'btn btn-primary' %> today!
    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Solves world hunger</h2>
        <p>Bloccit will deliver food and water to those in need, all over the planet of Earth.</p>
    </div>
    <div class="col-md-4">
        <h2>Eliminates poverty</h2>
        <p>Poor? Not no more! Bloccit will deliver money and education to those in need, all over the planet.</p>
    </div>
    <div class="col-md-4">
        <h2>Makes you better looking</h2>
        <p>Bloccit will make you better looking: it's scientifically proven to square up your jawline and make you smell like cocoa butter.</p>
    </div>
</div>